#management.endpoint.health.show-details=always  #actuator health端口总是暴露
#management.endpoints.web.exposure.include=*
#
#info.app-name=spring-boot-demo
#info.author=lucas
#info.email=xx@email


spring:
  datasource:
    url: jdbc:mysql://rm-bp19y5ow28vo3bh2exo.mysql.rds.aliyuncs.com:3306/content_center
    hikari:
      username: zyb123456789
      password: zyb123456789!
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 7cf55ebe-8005-4c48-a506-36b219d8ae62
        cluster-name: ZJ
    sentinel:
#      filter:N
#        enabled: false
      # 指定 sentinel 控制台的地址
      transport:
        dashboard: localhost:8080
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          addBonus-out-0:
            producer:
              group: tx-add-bonus-group
              transactional: true
      bindings:
        addBonus-out-0:
          # 用于指定topic
          destination: add-bonus
  application:
    name: content-center

  main:
    allow-bean-definition-overriding: true

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.wistron.springboot.springbootlearn.configuration.NacosWeightedRule

#  ribbon 开启饥饿加载
#ribbon:
#  eager-load:
#    enable: true
#    clients: user-center

#spring 中开启该类的注释  并且feign的日志级别都是DEBUG
logging:
  level:
    com.wistron.springboot.springbootlearn.feignclient.UserCenterFeignClient: debug
#feign 日志进行属性配置
feign:
  # 为Feign整合 Sentinel
#  sentinel:
#    enabled: true
  client:
    config:
      # default: 即为feign的全局配置
      user-center:
        loggerLevel: BASIC
  httpclient:
    # 开启Feign 使用apache httpclient做请求
    enabled: ture
    # feign的最大连接数
    max-connnections: 200
    # feign单个路径的最大连接数
    max-connnections-per-route: 50

#  暴露所有web端口   这里为了进行暴露 sentinel服务端口
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        #需要注意 yml中需要 加上''
        include: '*'
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
#    坑： 必须指定group
    group: test-group